import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mergeVertices} from 'three/addons/utils/BufferGeometryUtils.js';
import {buildReliefGeometry} from './algorithm.js';
const byId=id=>document.getElementById(id),status=byId('status');let imageData=null,sourceName='reference image',model=null;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.01,1000),renderer=new THREE.WebGLRenderer({canvas:byId('preview'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));scene.add(new THREE.HemisphereLight(0xffffff,0x354b55,2.5));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(4,7,6);scene.add(light);camera.position.set(5,3,8);const controls=new OrbitControls(camera,renderer.domElement);
function show(result){if(model){scene.remove(model);model.geometry.dispose();model.material.dispose();}let geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(result.positions,3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute(result.uvs,2));if(result.meta?.recoveredV30||result.meta?.hybridV46||result.meta?.hybridV47){const welded=mergeVertices(geometry,1e-4);geometry.dispose();geometry=welded;}geometry.computeVertexNormals();geometry.computeBoundingBox();model=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:0xe2e8e4,roughness:.72,side:THREE.DoubleSide}));scene.add(model);const center=geometry.boundingBox.getCenter(new THREE.Vector3()),size=geometry.boundingBox.getSize(new THREE.Vector3()).length()||1;controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(size*.75,size*.4,size*1.3));camera.far=Math.max(1000,size*10);camera.updateProjectionMatrix();controls.update();}
function render(){const canvas=renderer.domElement,w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.render(scene,camera);requestAnimationFrame(render);}render();
function number(id,fallback,min,max){const value=Number(byId(id).value);return Math.min(max,Math.max(min,Number.isFinite(value)?value:fallback));}
function build(options,requestId=null){try{const result=buildReliefGeometry(options);show(result);status.textContent=(result.positions.length/9)+' triangles ready. Choose Add mesh to BWS above.';parent.postMessage({type:'bws-plugin-mesh',requestId,name:options.sourceName||'Image mesh',geometry:{positions:result.positions,uvs:result.uvs},meta:result.meta},'*');}catch(error){status.textContent='Could not build mesh: '+error.message;parent.postMessage({type:'bws-plugin-mesh-error',requestId,message:error.message},'*');}}
byId('reliefImageBtn').onclick=()=>byId('reliefImageFile').click();
byId('reliefImageFile').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>16000000)throw Error('Choose an image smaller than 16 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Image could not be read.'));reader.readAsDataURL(file);});const image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('Image could not be decoded.'));img.src=data;});if(image.width*image.height>16000000)throw Error('Choose an image smaller than 16 megapixels.');const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0);imageData=ctx.getImageData(0,0,canvas.width,canvas.height);sourceName=file.name;byId('reliefImageName').textContent=file.name+' ('+image.width+' x '+image.height+')';status.textContent='Image loaded. Adjust settings and choose Create image mesh.';}catch(error){status.textContent=error.message;}};
byId('createReliefMeshBtn').onclick=()=>{if(!imageData){status.textContent='Load an image first.';return;}build({imageData,cols:Math.round(number('reliefGridXInput',160,8,160)),rows:Math.round(number('reliefGridYInput',220,8,220)),scale:number('reliefScaleInput',6,.5,20),depth:number('reliefDepthInput',.9,0,5),back:number('reliefBackInput',.22,0,3),threshold:number('reliefThresholdInput',70,0,255),detailStrength:number('reliefDetailInput',100,0,200)/100,smoothPasses:4,darkForeground:byId('reliefDarkForegroundInput').checked,sourceMode:byId('reliefSourceModeInput').value,buildMode:byId('reliefBuildModeInput').value,sourceName});};
window.addEventListener('message',event=>{if(event.source===parent&&event.data?.type==='bws-plugin-generate')build(event.data.options,event.data.requestId);});parent.postMessage({type:'bws-plugin-ready'},'*');
