import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const byId=id=>document.getElementById(id),canvas=byId('preview'),status=byId('status'),scene=new THREE.Scene();scene.background=new THREE.Color('#101a20');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const camera=new THREE.PerspectiveCamera(42,1,.01,1000);camera.position.set(6,4,8);const controls=new OrbitControls(camera,canvas);scene.add(new THREE.HemisphereLight(0xcde4ff,0x38423a,1.2));
const main=new THREE.SpotLight(0xffe4c4,10),mirror=new THREE.SpotLight(0xc8deff,10);for(const light of [main,mirror]){light.castShadow=true;light.shadow.mapSize.set(1024,1024);light.shadow.normalBias=.03;scene.add(light,light.target);}const guides=[new THREE.SpotLightHelper(main),new THREE.SpotLightHelper(mirror)];scene.add(...guides);let models=[],textures=[];
function value(id,fallback){const v=Number(byId(id).value);return Number.isFinite(v)?v:fallback;}
function lighting(){const x=value('lightPosXInput',-6),y=value('lightPosYInput',5),z=value('lightPosZInput',6);main.position.set(x,y,z);mirror.position.set(-x,y,z);const aim=[value('lightTargetXInput',0),value('lightTargetYInput',1.5),value('lightTargetZInput',0)];for(const light of [main,mirror]){light.target.position.fromArray(aim);light.intensity=Math.max(0,Math.min(40,value('lightIntensityInput',10)));light.angle=THREE.MathUtils.degToRad(Math.max(5,Math.min(80,value('lightAngleInput',24))));light.penumbra=.35;}main.visible=byId('enablePrimaryLightInput').checked;mirror.visible=byId('enableMirrorLightInput').checked;for(const guide of guides){guide.visible=byId('showLightGuidesInput').checked;guide.update();}}
for(const input of document.querySelectorAll('#sceneRenderingTools input'))input.addEventListener('input',lighting);lighting();
byId('fullscreen').onclick=async()=>{try{await canvas.requestFullscreen();}catch(error){status.textContent='Fullscreen unavailable: '+error.message;}};
window.addEventListener('message',event=>{if(event.source!==parent||event.data?.type!=='bws-model-snapshot')return;try{
 for(const mesh of models){scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}for(const texture of textures)texture.dispose();models=[];textures=[];selectedParts.clear();selectionBox.visible=false;
 const snapshot=event.data.snapshot,library=new Map(snapshot.textures.map(t=>[t.name,t])),loader=new THREE.BufferGeometryLoader(),textureLoader=new THREE.TextureLoader(),maps=new Map();
 for(const part of snapshot.meshes){const material=new THREE.MeshStandardMaterial({color:part.color,roughness:.72}),entry=library.get(part.userData.textureName);if(entry?.dataUrl){let texture=maps.get(entry.name);if(!texture){texture=textureLoader.load(entry.dataUrl);texture.colorSpace=THREE.SRGBColorSpace;maps.set(entry.name,texture);textures.push(texture);}material.map=texture;}const mesh=new THREE.Mesh(loader.parse(part.geometry),material);mesh.matrixAutoUpdate=false;mesh.matrix.fromArray(part.matrixWorld);mesh.name=part.name||'Part '+(models.length+1);mesh.visible=!part.userData.hidden;mesh.geometry.computeBoundingBox();const bounds=mesh.geometry.boundingBox.clone().applyMatrix4(mesh.matrix);mesh.userData.damageBase={matrix:mesh.matrix.clone(),color:material.color.clone(),roughness:material.roughness,visible:mesh.visible,center:bounds.getCenter(new THREE.Vector3()),size:bounds.getSize(new THREE.Vector3()),seed:damageHash(String(part.userData.id||mesh.name)+'/'+models.length),amount:0};mesh.castShadow=mesh.receiveShadow=true;models.push(mesh);scene.add(mesh);}
 const box=new THREE.Box3();for(const mesh of models)if(mesh.visible)box.expandByObject(mesh);if(!box.isEmpty()){const center=box.getCenter(new THREE.Vector3()),size=Math.max(.1,box.getSize(new THREE.Vector3()).length());controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(size*.7,size*.4,size*1.25));camera.far=Math.max(1000,size*10);camera.updateProjectionMatrix();for(const [axis,n]of [['X',center.x],['Y',center.y],['Z',center.z]])byId('lightTarget'+axis+'Input').value=n;lighting();controls.update();}damageBounds.copy(box);byId('damageAmount').value=0;byId('damageValue').textContent='0%';renderPartList();selectionChanged();status.textContent=models.length+' parts received. Click parts to select; drag to orbit. Shift-click adds to selection.';
 }catch(error){status.textContent='Could not load this model: '+error.message;}});

// Every change is derived from the received base state, never from an earlier preview.
const selectedParts=new Set(),damageBounds=new THREE.Box3(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
const selectionBox=new THREE.Box3Helper(new THREE.Box3(),0x60d9c1);selectionBox.visible=false;scene.add(selectionBox);
function damageHash(text){let n=2166136261;for(const c of text){n^=c.charCodeAt(0);n=Math.imul(n,16777619);}return n>>>0;}
function noise(seed,salt){let n=(seed^Math.imul(salt,374761393))>>>0;n=Math.imul(n^(n>>>13),1274126177);return ((n^(n>>>16))>>>0)/4294967295;}
function renderPartList(){const list=byId('damageParts'),query=byId('partSearch').value.toLowerCase();list.replaceChildren();const fragment=document.createDocumentFragment();models.forEach((mesh,index)=>{if(!mesh.userData.damageBase.visible||!mesh.name.toLowerCase().includes(query))return;const option=document.createElement('option');option.value=index;option.textContent=mesh.name;option.selected=selectedParts.has(mesh);fragment.append(option);});list.append(fragment);}
function selectionChanged(){byId('selectionCount').textContent=selectedParts.size+' selected';const box=new THREE.Box3();for(const mesh of selectedParts)if(mesh.visible)box.union(mesh.geometry.boundingBox.clone().applyMatrix4(mesh.matrix));selectionBox.box.copy(box);selectionBox.visible=!box.isEmpty();for(const option of byId('damageParts').options)option.selected=selectedParts.has(models[Number(option.value)]);byId('damageSummary').textContent=models.filter(m=>m.userData.damageBase.amount>0).length+' parts weathered or damaged. Original BWS model unchanged.';}
function applyDamage(mesh,amount){const base=mesh.userData.damageBase;mesh.matrix.copy(base.matrix);mesh.visible=base.visible;mesh.material.color.copy(base.color);mesh.material.roughness=base.roughness;base.amount=amount;if(!base.visible)return;
 mesh.material.color.lerp(new THREE.Color('#443b30'),amount*(.35+noise(base.seed,1)*.35));mesh.material.roughness=base.roughness+(1-base.roughness)*amount;
 const loosen=Math.max(0,amount-.4)/.6,collapse=noise(base.seed,2)<Math.max(0,amount-.65)*.75;
 if(loosen>0&&noise(base.seed,3)<.4){const center=base.center,target=center.clone(),extent=damageBounds.getSize(new THREE.Vector3()).length()||1;target.x+=(noise(base.seed,4)-.5)*extent*.035*loosen;target.z+=(noise(base.seed,5)-.5)*extent*.035*loosen;
 if(collapse){target.y=damageBounds.min.y+base.size.y*.15;target.x+=(noise(base.seed,6)-.5)*extent*.15;target.z+=(noise(base.seed,7)-.5)*extent*.15;}
 const tilt=(collapse?1.2:.16)*loosen,rotation=new THREE.Matrix4().makeRotationFromEuler(new THREE.Euler((noise(base.seed,8)-.5)*tilt,(noise(base.seed,9)-.5)*tilt,(noise(base.seed,10)-.5)*tilt));mesh.matrix.makeTranslation(target.x,target.y,target.z).multiply(rotation).multiply(new THREE.Matrix4().makeTranslation(-center.x,-center.y,-center.z)).multiply(base.matrix);
 }
 // Missing pieces create reversible gaps; no geometry or original data is deleted.
 if(amount>.85&&noise(base.seed,11)<(amount-.85)*.45)mesh.visible=false;mesh.matrixWorldNeedsUpdate=true;
}
function updateDamage(){const amount=Number(byId('damageAmount').value)/100;byId('damageValue').textContent=Math.round(amount*100)+'%';if(!selectedParts.size){byId('damageSummary').textContent='Select parts, or choose Select all, before changing damage.';return;}for(const mesh of selectedParts)applyDamage(mesh,amount);selectionChanged();}
byId('damageAmount').addEventListener('input',updateDamage);
byId('partSearch').oninput=renderPartList;
byId('damageParts').onchange=()=>{for(const option of byId('damageParts').options){const mesh=models[Number(option.value)];option.selected?selectedParts.add(mesh):selectedParts.delete(mesh);}selectionChanged();};
byId('selectAllParts').onclick=()=>{for(const mesh of models)if(mesh.userData.damageBase.visible)selectedParts.add(mesh);selectionChanged();};
byId('clearParts').onclick=()=>{selectedParts.clear();selectionChanged();};
byId('resetSelected').onclick=()=>{for(const mesh of selectedParts)applyDamage(mesh,0);byId('damageAmount').value=0;byId('damageValue').textContent='0%';selectionChanged();};
byId('resetDamage').onclick=()=>{for(const mesh of models)applyDamage(mesh,0);byId('damageAmount').value=0;byId('damageValue').textContent='0%';selectionChanged();};
let down=null;canvas.addEventListener('pointerdown',event=>{if(event.button===0)down={x:event.clientX,y:event.clientY};});canvas.addEventListener('pointercancel',()=>{down=null;});canvas.addEventListener('pointerup',event=>{if(!down||event.button!==0)return;const moved=Math.hypot(event.clientX-down.x,event.clientY-down.y);down=null;if(moved>5)return;const rect=canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(models.filter(m=>m.visible),false)[0]?.object;if(!event.shiftKey&&!event.ctrlKey&&!event.metaKey)selectedParts.clear();if(hit){selectedParts.has(hit)?selectedParts.delete(hit):selectedParts.add(hit);}selectionChanged();});

function render(){const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();for(const guide of guides)if(guide.visible)guide.update();renderer.render(scene,camera);requestAnimationFrame(render);}render();parent.postMessage({type:'bws-plugin-ready'},'*');
